export const eventsData = {
  "Secondary Boys": {
    ARCHERY: [
      "70M Distance",
      "60M Distance",
      "50M Distance",
      "30M Distance",
      "1140 Round",
      "Olympic Round (Ind'l 70M)",
      "Olympic Team Even (70M)",
      "Mixed Team (60M)",
    ],
    ARNIS: [
      "Ind’l Solo Baston (Single Weapon)",
      "Ind’l Doble Baston (Double Weapon)",
      "Team (Synd)-Solo Baston (Single Weapon)",
      "Team (Synd)-Double Baston (Double Weapon)",
      "EVENT Individual Espada Y Daga",
      "EVENT Team Espada Y Daga",
      "Pin Weight (43kg up to 47kg)",
      "Bantam-weight (47kg up to 51kg)",
      "Feather-weight (51kg up to 55kg)",
      "Extra Light weight (55kg up to 60kg)",
      "Half Light weight (60kg up to 65kg)",
    ],
    ATHLETICS: {
      TRACKS: [
        "100M Dash",
        "200M Dash",
        "400M Dash",
        "800M Run",
        "1500M Run",
        "110MH",
        "400MH",
        "3000M Steeple Chase",
        "5000M Run",
        "4x100M Relay",
        "4x400M Relay",
        "2000M Walk",
      ],
      THROWS: ["Javelin Throw", "Discus Throw", "Shot Put"],
      JUMPS: ["High Jump", "Long Jump", "Triple Jump", "Pole Vault"],
    },
    "RACKET GAMES": {
      BADMINTON: ["Singles", "Doubles", "Mixed"],
      "TABLE TENNIS": ["Singles", "Doubles", "Mixed Doubles"],
      TENNIS: ["Singles", "Doubles"],
    },
    "BALL GAMES": [
      "Baseball",
      "Basketball (Regular)",
      "Basketball (3 on 3)",
      "Football",
      "Volleyball",
    ],
    "SEPAK TAKRAW": ["Best Regu", "Team"],
    BILLIARDS: ["8 Balls", "9 Balls"],
    CHESS: [
      "Standard - Individual",
      "Standard - Team",
      "Rapid - Individual",
      "Rapid - Team",
      "Blitz - Individual",
      "Blitz – Team",
    ],
    "PENCAK SILAT": {
      COMBAT: [
        "Class A Over 42kg up to 45kg",
        "Class B Over 45kg up to 48kg",
        "Class C Over 48kg up to 51kg",
        "Class D Over 51kg up to 54kg",
        "Class E Over 54kg up to 57kg",
      ],
      DEMO: [
        "Tunggal-Ind’l Weapon",
        "Ganda – Double Weapon",
        "Regu-Team Artistic",
      ],
      "MODERN STANDARD SINGLE DANCE": [
        "Waltz",
        "Tango",
        "V-Waltz",
        "Foxtrot",
        "Quickstep",
        "Grade A - W, T, VW, SF, Q",
      ],
    },
    GYMNASTICS: {
      "MAG CLUSTER 3": [
        "Floor Exercise",
        "Vaulting Table",
        "Mushroom",
        "Individual All Around",
        "Horizontal Bar",
        "Team",
      ],
    },
    BOXING: [
      "Pin Weight (SB)",
      "Light Flyweight (SB)",
      "Pin Weight (JB)",
      "Light Flyweight (JB)",
      "Flyweight (JB)",
      "Light Bantam weight (JB)",
      "Bantam Weight (JB)",
      "Minimum Weight (YB)",
      "Flyweight (YB)",
      "Bantam Weight (YB)",
    ],
    SWIMMING: {
      TRACKS: [
        "50M Back Stroke",
        "50M Breaststroke",
        "50M Butterfly",
        "50M Free Style",
        "100M Back Stroke",
        "100M Butterfly",
        "100M Freestyle",
        "200M Backstroke",
        "200M Breaststroke",
        "200M Butterfly",
        "200M Free style",
        "400M Free Style",
        "800M Free Style",
        "1500M Free Style",
        "200M Individual Medley",
        "400M Individual Medley",
        "200M Free style Relay",
        "200M Medley Relay",
        "400M Free style Relay",
        "400M Medley Relay",
      ],
    },
    TAEKWONDO: {
      KYORUGI: [
        "Fin Weight",
        "Fly Weight",
        "Bantam Weight",
        "Feather Weight",
        "Light Weight",
        "Welter Weight",
        "Lt Middle Weight",
      ],
      POOMSAE: [
        "Group A - Individual",
        "Group B - Individual",
        "Team - Event",
        "Mix Pair",
      ],
    },
    WUSHU: {
      "Wushu – Boys (Group A)": ["48kgs", "52kgs", "56kgs"],
      "Wushu – Boys (Group B)": ["42kgs", "45kgs", "48kgs"],
    },
    WRESTLING: [
      "Cadet 42kgs",
      "Cadet 46kgs",
      "Cadet 50kgs",
      "Cadet 54kgs",
      "Junior 54kgs",
      "Junior 58kgs",
      "Junior 62kgs",
      "Junior 66kgs",
    ],
  },
  "Secondary Girls": {
    ARCHERY: [
      "70M Distance",
      "60M Distance",
      "50M Distance",
      "30M Distance",
      "1140 Round",
      "Olympic Round (Ind'l 70M)",
      "Olympic Team Even (70M)",
      "Mixed Team (60M)",
    ],
    ARNIS: [
      "Ind’l Solo Baston (Single Weapon)",
      "Ind’l Doble Baston (Double Weapon)",
      "Team (Synd)-Solo Baston (Single Weapon)",
      "Team (Synd)-Double Baston (Double Weapon)",
      "EVENT Individual Espada Y Daga",
      "EVENT Team Espada Y Daga",
      "Pin Weight (43kg up to 47kg)",
      "Bantam-weight (47kg up to 51kg)",
      "Feather-weight (51kg up to 55kg)",
      "Extra Light weight (55kg up to 60kg)",
      "Half Light weight (60kg up to 65kg)",
    ],
    ATHLETICS: {
      TRACKS: [
        "100M Dash",
        "200M Dash",
        "400M Dash",
        "800M Run",
        "1500M Run",
        "100MH",
        "400MH",
        "3000M Steeple Chase",
        "5000M Run",
        "4x100M Relay",
        "4x400M Relay",
        "2000M Walk",
      ],
      THROWS: ["Javelin Throw", "Discus Throw", "Shot Put"],
      JUMPS: ["High Jump", "Long Jump", "Triple Jump", "Pole Vault"],
    },
    "RACKET GAMES": {
      BADMINTON: ["Singles", "Doubles", "Mixed"],
      "TABLE TENNIS": ["Singles", "Doubles", "Mixed Doubles"],
      TENNIS: ["Singles", "Doubles"],
    },
    "BALL GAMES": [
      "Baseball",
      "Basketball (Regular)",
      "Basketball (3 on 3)",
      "Football",
      "Volleyball",
    ],
    "SEPAK TAKRAW": ["Best Regu", "Team"],
    BILLIARDS: ["8 Balls", "9 Balls"],
    CHESS: [
      "Standard - Individual",
      "Standard - Team",
      "Rapid - Individual",
      "Rapid - Team",
      "Blitz - Individual",
      "Blitz – Team",
    ],
    "PENCAK SILAT": {
      COMBAT: [
        "Class A Over 42kg up to 45kg",
        "Class B Over 45kg up to 48kg",
        "Class C Over 48kg up to 51kg",
        "Class D Over 51kg up to 54kg",
        "Class E Over 54kg up to 57kg",
      ],
      DEMO: [
        "Tunggal-Ind’l Weapon",
        "Ganda – Double Weapon",
        "Regu-Team Artistic",
      ],
      "MODERN STANDARD SINGLE DANCE": [
        "Waltz",
        "Tango",
        "V-Waltz",
        "Foxtrot",
        "Quickstep",
        "Grade A - W, T, VW, SF, Q",
      ],
    },
    GYMNASTICS: {
      "MAG CLUSTER 3": [
        "Floor Exercise",
        "Vaulting Table",
        "Mushroom",
        "Individual All Around",
        "Horizontal Bar",
        "Team",
      ],
    },
    BOXING: [
      "Pin Weight (SB)",
      "Light Flyweight (SB)",
      "Pin Weight (JB)",
      "Light Flyweight (JB)",
      "Flyweight (JB)",
      "Light Bantam weight (JB)",
      "Bantam Weight (JB)",
      "Minimum Weight (YB)",
      "Flyweight (YB)",
      "Bantam Weight (YB)",
    ],
    SWIMMING: {
      TRACKS: [
        "50M Back Stroke",
        "50M Breaststroke",
        "50M Butterfly",
        "50M Free Style",
        "100M Back Stroke",
        "100M Butterfly",
        "100M Freestyle",
        "200M Backstroke",
        "200M Breaststroke",
        "200M Butterfly",
        "200M Free style",
        "400M Free Style",
        "800M Free Style",
        "1500M Free Style",
        "200M Individual Medley",
        "400M Individual Medley",
        "200M Free style Relay",
        "200M Medley Relay",
        "400M Free style Relay",
        "400M Medley Relay",
      ],
    },
    TAEKWONDO: {
      KYORUGI: [
        "Fin Weight",
        "Fly Weight",
        "Bantam Weight",
        "Feather Weight",
        "Light Weight",
        "Welter Weight",
        "Lt Middle Weight",
      ],
      POOMSAE: [
        "Group A - Individual",
        "Group B - Individual",
        "Team - Event",
        "Mix Pair",
      ],
    },
    WUSHU: {
      "Wushu – Girls (Group A)": ["48kgs", "52kgs", "56kgs"],
      "Wushu – Girls (Group B)": ["42kgs", "45kgs", "48kgs"],
    },
    WRESTLING: [
      "Cadet 42kgs",
      "Cadet 46kgs",
      "Cadet 50kgs",
      "Cadet 54kgs",
      "Junior 54kgs",
      "Junior 58kgs",
      "Junior 62kgs",
      "Junior 66kgs",
    ],
  },
  Elementary: {
    // Placeholder for elementary events
  },
};
