import secondaryEventsBoys from './secondaryEventsBoys';

export const EVENTS = {
  ELEMENTARY: {
    BOYS: {
      ARCHERY: [
        "15 M 1st Distance",
        "15 M 2nd Distance",
        "20 M 1st Distance",
        "20 M 2nd Distance",
        "Single FITA 1140 Round",
        "Olympic Round Ind'l",
      ],
      ARNIS: [
        "Individual Single Weapon NT",
        "Individual Double Weapon NT",
        "Team Likha-Synchronized Single Weapon NT",
        "Team Likha-Synchronized Double Weapon NT",
        "Anyo-Individual S&D Weapon NT",
        "Anyo Event Team S&D",
        "Pair Team Likha Anyo Double Baston",
      ],
      ATHLETICS: [
        "TRACKS - 100M Dash",
        "TRACKS - 200M Dash",
        "TRACKS - 400M Dash",
        "TRACKS - 800M Run",
        "TRACKS - 1500M Run",
        "TRACKS - 100MH",
        "TRACKS - 400MH",
        "TRACKS - 4x100M Relay",
        "TRACKS - 4x400M Relay",
        "THROWS - Javelin Throw",
        "THROWS - Discus Throw",
        "THROWS - Shot Put",
        "JUMPS - High Jump",
        "JUMPS - Long Jump",
        "JUMPS - Triple Jump",
      ],
      BALL_GAMES: [
        "Baseball",
        "Basketball Regular",
        "Basketball 3 on 3 - Demo Sports",
        "Football",
        "Volleyball",
      ],
      SEPAK_TAKRAW: ["Junior - Team", "Double Takraw"],
      CHESS: [
        "Standard - Individual",
        "Standard - Team",
        "Rapid - Individual",
        "Rapid - Team",
        "Blitz - Individual",
        "Blitz – Team",
      ],
      RACKET_GAMES: [
        "BADMINTON - Singles",
        "BADMINTON - Doubles",
        "BADMINTON - Mixed",
        "TABLE_TENNIS - Singles",
        "TABLE_TENNIS - Doubles",
        "TABLE_TENNIS - Mixed Doubles",
        "TENNIS - Singles",
        "TENNIS - Doubles",
      ],
      DANCE_SPORTS: [
        "LATIN_SINGLE_DANCE - Chacha",
        "LATIN_SINGLE_DANCE - Samba",
        "LATIN_SINGLE_DANCE - Rumba",
        "LATIN_SINGLE_DANCE - Pasadoble",
        "LATIN_SINGLE_DANCE - Jive",
        "LATIN_SINGLE_DANCE - Grade A - C, S, R, P, D, J",
        "MODERN_STANDARD_SINGLE_DANCE - Waltz",
        "MODERN_STANDARD_SINGLE_DANCE - Tango",
        "MODERN_STANDARD_SINGLE_DANCE - V-Waltz",
        "MODERN_STANDARD_SINGLE_DANCE - Foxtrot",
        "MODERN_STANDARD_SINGLE_DANCE - Quickstep",
        "MODERN_STANDARD_SINGLE_DANCE - Grade A - W, T, VW, SF, Q",
      ],
      GYMNASTICS: [
        "MAG_CLUSTER_2 - Floor Exercise",
        "MAG_CLUSTER_2 - Vaulting Table",
        "MAG_CLUSTER_2 - Mushroom",
        "MAG_CLUSTER_2 - Individual Around",
        "MAG_CLUSTER_2 - Horizontal Bar",
        "MAG_CLUSTER_1 - Floor Exercise",
        "MAG_CLUSTER_1 - Vaulting Table",
        "MAG_CLUSTER_1 - Mushroom",
        "MAG_CLUSTER_1 - Individual Around",
        "MAG_CLUSTER_1 - Horizontal Bar",
        "WAG_CLUSTER_1 - Floor Exercise",
        "WAG_CLUSTER_1 - Balance Beam",
        "WAG_CLUSTER_1 - Vault",
        "WAG_CLUSTER_1 - Single Bar",
        "WAG_CLUSTER_1 - Individual All Around",
        "WAG_CLUSTER_1 - Team",
        "WAG_CLUSTER_2 - Floor Exercise",
        "WAG_CLUSTER_2 - Balance Beam",
        "WAG_CLUSTER_2 - Vault",
        "WAG_CLUSTER_2 - Single Bar",
        "WAG_CLUSTER_2 - Individual All Around",
        "WAG_CLUSTER_2 - Team",
        "RG - Ball",
        "RG - Rope",
        "RG - Hoop",
        "RG - Free Hand",
        "RG - Individual All Around",
        "RG - Team",
        "AEROGYMNASTICS - Individual Men",
        "AEROGYMNASTICS - Individual Women",
        "AEROGYMNASTICS - Trio",
        "AEROGYMNASTICS - Mix Pair",
        "AEROGYMNASTICS - Aero Dance",
        "AEROGYMNASTICS - Team",
      ],
      SWIMMING: [
        "TRACKS - 50M Back Stroke",
        "TRACKS - 50M Breaststroke",
        "TRACKS - 50M Butterfly",
        "TRACKS - 50M Free Style",
        "TRACKS - 100M Back Stroke",
        "TRACKS - 100M Free Style",
        "TRACKS - 200M Freestyle",
        "TRACKS - 200M Individual Medley",
        "TRACKS - 400M Free Style",
        "TRACKS - 4x50M Medley Relay",
        "TRACKS - 4x50M Medley Relay",
        "TRACKS - 4x100M Free Style Relay",
        "TRACKS - 4x100M Medley Relay",
      ],
      TAEKWONDO: [
        "KYORUGI - Over 144cm to 150cm",
        "KYORUGI - Over 152cm to 158cm",
        "KYORUGI - Over 160cm",
        "KYORUGI - Group A – Individual",
        "POOMSAE - Group A - Individual",
        "POOMSAE - Group B - Individual",
        "POOMSAE - Team - Event",
        "POOMSAE - Mix Pair",
      ],
    },
    GIRLS: {
      ARCHERY: [
        "15 M 1st Distance",
        "15 M 2nd Distance",
        "20 M 1st Distance",
        "20 M 2nd Distance",
        "Single FITA 1140 Round",
        "Olympic Round Ind'l",
      ],
      ARNIS: [
        "Individual Single Weapon NT",
        "Individual Double Weapon NT",
        "Team Likha-Synchronized Single Weapon NT",
        "Team Likha-Synchronized Double Weapon NT",
        "Anyo-Individual S&D Weapon NT",
        "Anyo Event Team S&D",
        "Pair Team Likha Anyo Double Baston",
      ],
      ATHLETICS: [
        "TRACKS - 100M Dash",
        "TRACKS - 200M Dash",
        "TRACKS - 400M Dash",
        "TRACKS - 800M Run",
        "TRACKS - 1500M Run",
        "TRACKS - 100MH",
        "TRACKS - 400MH",
        "TRACKS - 4x100M Relay",
        "TRACKS - 4x400M Relay",
        "THROWS - Javelin Throw",
        "THROWS - Discus Throw",
        "THROWS - Shot Put",
        "JUMPS - High Jump",
        "JUMPS - Long Jump",
        "JUMPS - Triple Jump",
      ],
      BALL_GAMES: ["Softball", "Volleyball"],
      CHESS: [
        "Standard - Individual",
        "Standard - Team",
        "Rapid - Individual",
        "Rapid - Team",
        "Blitz - Individual",
        "Blitz – Team",
      ],
      RACKET_GAMES: [
        "BADMINTON - Singles",
        "BADMINTON - Doubles",
        "BADMINTON - Mixed",
        "TABLE_TENNIS - Singles",
        "TABLE_TENNIS - Doubles",
        "TABLE_TENNIS - Mixed Doubles",
        "TENNIS - Singles",
        "TENNIS - Doubles",
      ],
      DANCE_SPORTS: [
        "LATIN_SINGLE_DANCE - Chacha",
        "LATIN_SINGLE_DANCE - Samba",
        "LATIN_SINGLE_DANCE - Rumba",
        "LATIN_SINGLE_DANCE - Pasadoble",
        "LATIN_SINGLE_DANCE - Jive",
        "LATIN_SINGLE_DANCE - Grade A - C, S, R, P, D, J",
        "MODERN_STANDARD_SINGLE_DANCE - Waltz",
        "MODERN_STANDARD_SINGLE_DANCE - Tango",
        "MODERN_STANDARD_SINGLE_DANCE - V-Waltz",
        "MODERN_STANDARD_SINGLE_DANCE - Foxtrot",
        "MODERN_STANDARD_SINGLE_DANCE - Quickstep",
        "MODERN_STANDARD_SINGLE_DANCE - Grade A - W, T, VW, SF, Q",
      ],
      GYMNASTICS: [
        "MAG_CLUSTER_2 - Floor Exercise",
        "MAG_CLUSTER_2 - Vaulting Table",
        "MAG_CLUSTER_2 - Mushroom",
        "MAG_CLUSTER_2 - Individual Around",
        "MAG_CLUSTER_2 - Horizontal Bar",
        "MAG_CLUSTER_1 - Floor Exercise",
        "MAG_CLUSTER_1 - Vaulting Table",
        "MAG_CLUSTER_1 - Mushroom",
        "MAG_CLUSTER_1 - Individual Around",
        "MAG_CLUSTER_1 - Horizontal Bar",
        "WAG_CLUSTER_1 - Floor Exercise",
        "WAG_CLUSTER_1 - Balance Beam",
        "WAG_CLUSTER_1 - Vault",
        "WAG_CLUSTER_1 - Single Bar",
        "WAG_CLUSTER_1 - Individual All Around",
        "WAG_CLUSTER_1 - Team",
        "WAG_CLUSTER_2 - Floor Exercise",
        "WAG_CLUSTER_2 - Balance Beam",
        "WAG_CLUSTER_2 - Vault",
        "WAG_CLUSTER_2 - Single Bar",
        "WAG_CLUSTER_2 - Individual All Around",
        "WAG_CLUSTER_2 - Team",
        "RG - Ball",
        "RG - Rope",
        "RG - Hoop",
        "RG - Free Hand",
        "RG - Individual All Around",
        "RG - Team",
        "AEROGYMNASTICS - Individual Men",
        "AEROGYMNASTICS - Individual Women",
        "AEROGYMNASTICS - Trio",
        "AEROGYMNASTICS - Mix Pair",
        "AEROGYMNASTICS - Aero Dance",
        "AEROGYMNASTICS - Team",
      ],
      SWIMMING: [
        "TRACKS - 50M Back Stroke",
        "TRACKS - 50M Breaststroke",
        "TRACKS - 50M Butterfly",
        "TRACKS - 50M Free Style",
        "TRACKS - 100M Back Stroke",
        "TRACKS - 100M Butterfly",
        "TRACKS - 100M Freestyle",
        "TRACKS - 200M Backstroke",
        "TRACKS - 200M Breaststroke",
        "TRACKS - 200M Butterfly",
        "TRACKS - 200M Free style",
        "TRACKS - 400M Free Style",
        "TRACKS - 800M Free Style",
        "TRACKS - 1500M Free Style",
        "TRACKS - 200M Individual Medley",
        "TRACKS - 400M Individual Medley",
        "TRACKS - 200M Free style Relay",
        "TRACKS - 200M Medley Relay",
        "TRACKS - 400M Free style Relay",
        "TRACKS - 400M Medley Relay",
      ],
      TAEKWONDO: [
        "KYORUGI - Fin Weight",
        "KYORUGI - Fly Weight",
        "KYORUGI - Bantam Weight",
        "KYORUGI - Feather Weight",
        "KYORUGI - Light Weight",
        "KYORUGI - Welter Weight",
        "KYORUGI - Lt Middle Weight",
        "POOMSAE - Group A - Individual",
        "POOMSAE - Group B - Individual",
        "POOMSAE - Team - Event",
        "POOMSAE - Mix Pair",
      ],
    },
  },
  SECONDARY: {
    BOYS: {
      ARCHERY: [
        "70M Distance",
        "60M Distance",
        "50M Distance",
        "30M Distance",
        "1140 Round",
        "Olympic Round (Ind'l 70M)",
        "Olympic Team Even (70M)",
        "Mixed Team (60M)",
      ],
      ARNIS: [
        "Ind’l Solo Baston (Single Weapon)",
        "Ind’l Doble Baston (Double Weapon)",
        "Team (Synd)-Solo Baston (Single Weapon)",
        "Team (Synd)-Double Baston (Double Weapon)",
        "EVENT Individual Espada Y Daga",
        "EVENT Team Espada Y Daga",
        "Pin Weight (43kg up to 47kg)",
        "Bantam-weight (47kg up to 51kg)",
        "Feather-weight (51kg up to 55kg)",
        "Extra Light weight (55kg up to 60kg)",
        "Half Light weight (60kg up to 65kg)",
      ],
      ATHLETICS: [
        "TRACKS - 100M Dash",
        "TRACKS - 200M Dash",
        "TRACKS - 400M Dash",
        "TRACKS - 800M Run",
        "TRACKS - 1500M Run",
        "TRACKS - 110MH",
        "TRACKS - 400MH",
        "TRACKS - 3000M Steeple Chase",
        "TRACKS - 5000M Run",
        "TRACKS - 4x100M Relay",
        "TRACKS - 4x400M Relay",
        "TRACKS - 2000M Walk",
        "THROWS - Javelin Throw",
        "THROWS - Discus Throw",
        "THROWS - Shot Put",
        "JUMPS - High Jump",
        "JUMPS - Long Jump",
        "JUMPS - Triple Jump",
        "JUMPS -Pole Vault",
      ],
      RACKET_GAMES: [
        "BADMINTON - Singles",
        "BADMINTON - Doubles",
        "BADMINTON - Mixed",
        "TABLE TENNIS - Singles",
        "TABLE TENNIS - Doubles",
        "TABLE TENNIS - Mixed Doubles",
        "TENNIS - Singles",
        "TENNIS - Doubles",
      ],
      BALL_GAMES: [
        "Baseball",
        "Basketball (Regular)",
        "Basketball (3 on 3)",
        "Football",
        "Volleyball",
      ],
      SEPAK_TAKRAW: ["Best Regu", "Team"],
      BILLIARDS: ["8 Balls", "9 Balls"],
      CHESS: [
        "Standard - Individual",
        "Standard - Team",
        "Rapid - Individual",
        "Rapid - Team",
        "Blitz - Individual",
        "Blitz – Team",
      ],
      PENCAK_SILAT: [
        "COMBAT - Class A Over 42kg up to 45kg",
        "COMBAT - Class B Over 45kg up to 48kg",
        "COMBAT - Class C Over 48kg up to 51kg",
        "COMBAT - Class D Over 51kg up to 54kg",
        "COMBAT - Class E Over 54kg up to 57kg",
        "DEMO -Tunggal-Ind’l Weapon",
        "DEMO - Ganda – Double Weapon",
        "DEMO -Regu-Team Artistic",
      ],
      MODERN_STANDARD_SINGLE_DANCE: [
        "Waltz",
        "Tango",
        "V-Waltz",
        "Foxtrot",
        "Quickstep",
        "Grade A - W, T, VW, SF, Q",
      ],
      GYMNASTICS: [
        "MAG CLUSTER 3 - Floor Exercise",
        "MAG CLUSTER 3 - Vaulting Table",
        "MAG CLUSTER 3 - Mushroom",
        "MAG CLUSTER 3 - Individual All Around",
        "MAG CLUSTER 3 - Horizontal Bar",
        "Team",
      ],
      BOXING: [
        "Pin Weight (SB)",
        "Light Flyweight (SB)",
        "Pin Weight (JB)",
        "Light Flyweight (JB)",
        "Flyweight (JB)",
        "Light Bantam weight (JB)",
        "Bantam Weight (JB)",
        "Minimum Weight (YB)",
        "Flyweight (YB)",
        "Bantam Weight (YB)",
      ],
      SWIMMING: [
        "50M Back Stroke",
        "50M Breaststroke",
        "50M Butterfly",
        "50M Free Style",
        "100M Back Stroke",
        "100M Butterfly",
        "100M Freestyle",
        "200M Backstroke",
        "200M Breaststroke",
        "200M Butterfly",
        "200M Free style",
        "400M Free Style",
        "800M Free Style",
        "1500M Free Style",
        "200M Individual Medley",
        "400M Individual Medley",
        "200M Free style Relay",
        "200M Medley Relay",
        "400M Free style Relay",
        "400M Medley Relay",
      ],
      TAEKWONDO: [
        "KYORUGI - Fin Weight",
        "KYORUGI - Fly Weight",
        "KYORUGI - Bantam Weight",
        "KYORUGI - Feather Weight",
        "KYORUGI - Light Weight",
        "KYORUGI - Welter Weight",
        "KYORUGI - Lt Middle Weight",
        "POOMSAE - Group A - Individual",
        "POOMSAE - Group B - Individual",
        "POOMSAE - Team - Event",
        "POOMSAE - Mix Pair",
      ],
      WUSHU: [
        "Wushu – Boys (Group A) - 48kgs",
        "Wushu – Boys (Group A) - 52kgs",
        "Wushu – Boys (Group A) - 56kgs",
        "Wushu – Boys (Group B) - 42kgs",
        "Wushu – Boys (Group B) - 45kgs",
        "Wushu – Boys (Group B) - 48kgs",
      ],
      WRESTLING_FREESTYLE: [
        "Cadet 42kgs",
        "Cadet 46kgs",
        "Cadet 50kgs",
        "Cadet 54kgs",
        "Junior 54kgs",
        "Junior 58kgs",
        "Junior 62kgs",
        "Junior 66kgs",
      ],
    },
    GIRLS: {
      ARCHERY: [
        "70M Distance",
        "60M Distance",
        "50M Distance",
        "30M Distance",
        "1140 Round",
        "Olympic Round (Ind'l 70M)",
        "Olympic Team Even (70M)",
        "Mixed Team (60M)",
      ],
      ARNIS: [
        "Ind’l Solo Baston (Single Weapon)",
        "Ind’l Doble Baston (Double Weapon)",
        "Team (Synd)-Solo Baston (Single Weapon)",
        "Team (Synd)-Double Baston (Double Weapon)",
        "EVENT Individual Espada Y Daga",
        "EVENT Team Espada Y Daga",
        "Pin Weight (43kg up to 47kg)",
        "Bantam-weight (47kg up to 51kg)",
        "Feather-weight (51kg up to 55kg)",
        "Extra Light weight (55kg up to 60kg)",
        "Half Light weight (60kg up to 65kg)",
      ],
      ATHLETICS: [
        "TRACKS - 100M Dash",
        "TRACKS - 200M Dash",
        "TRACKS - 400M Dash",
        "TRACKS - 800M Run",
        "TRACKS - 1500M Run",
        "TRACKS - 110MH",
        "TRACKS - 400MH",
        "TRACKS - 3000M Steeple Chase",
        "TRACKS - 5000M Run",
        "TRACKS - 4x100M Relay",
        "TRACKS - 4x400M Relay",
        "TRACKS - 2000M Walk",
        "THROWS - Javelin Throw",
        "THROWS - Discus Throw",
        "THROWS - Shot Put",
        "JUMPS - High Jump",
        "JUMPS - Long Jump",
        "JUMPS - Triple Jump",
        "JUMPS -Pole Vault",
      ],
      RACKET_GAMES: [
        "BADMINTON - Singles",
        "BADMINTON - Doubles",
        "BADMINTON - Mixed",
        "TABLE TENNIS - Singles",
        "TABLE TENNIS - Doubles",
        "TABLE TENNIS - Mixed Doubles",
        "TENNIS - Singles",
        "TENNIS - Doubles",
      ],
      BALL_GAMES: [
        "Softball",
        "Basketball (Regular)",
        "Basketball (3 on 3)",
        "Futsal",
        "Volleyball",
      ],
      SEPAK_TAKRAW: ["Best Regu", "Double"],
      BILLIARDS: ["8 Balls", "9 Balls"],
      CHESS: [
        "Standard - Individual",
        "Standard - Team",
        "Rapid - Individual",
        "Rapid - Team",
        "Blitz - Individual",
        "Blitz – Team",
      ],
      PENCAK_SILAT: [
        "COMBAT - Class A Over 42kg up to 45kg",
        "COMBAT - Class B Over 45kg up to 48kg",
        "COMBAT - Class C Over 48kg up to 51kg",
        "COMBAT - Class D Over 51kg up to 54kg",
        "COMBAT - Class E Over 54kg up to 57kg",
        "DEMO -Tunggal-Ind’l Weapon",
        "DEMO - Ganda – Double Weapon",
        "DEMO -Regu-Team Artistic",
      ],
      GYMNASTICS: [
        "WAG CLUSTER 3 - Floor Exercise",
        "WAG CLUSTER 3 - Balance Beam",
        "WAG CLUSTER 3 - Vault",
        "WAG CLUSTER 3 - Individual All Around",
        "WAG CLUSTER 3 - Single Bar",
        "WAG CLUSTER 3 - Team",
        "RG - Ball",
        "RG - Club",
        "RG - Ribbon",
        "RG - Hoop",
        "RG - Individual All Around",
        "RG - Team",
        "AEROGYMNASTICS - Individual Men",
        "AEROGYMNASTICS - Individual Women",
        "AEROGYMNASTICS - Trio",
        "AEROGYMNASTICS - Mix Pair",
        "AEROGYMNASTICS - Aero Dance",
        "AEROGYMNASTICS - Team",
      ],
      SWIMMING: [
        "TRACKS - 50M Back Stroke",
        "TRACKS - 50M Breaststroke",
        "TRACKS - 50M Butterfly",
        "TRACKS - 50M Free Style",
        "TRACKS - 100M Back Stroke",
        "TRACKS - 100M Butterfly",
        "TRACKS - 100M Freestyle",
        "TRACKS - 200M Backstroke",
        "TRACKS - 200M Breaststroke",
        "TRACKS - 200M Butterfly",
        "TRACKS - 200M Free style",
        "TRACKS - 400M Free Style",
        "TRACKS - 800M Free Style",
        "TRACKS - 1500M Free Style",
        "TRACKS - 200M Individual Medley",
        "TRACKS - 400M Individual Medley",
        "TRACKS - 200M Free style Relay",
        "TRACKS - 200M Medley Relay",
        "TRACKS - 400M Free style Relay",
        "TRACKS - 400M Medley Relay",
      ],
      TAEKWONDO: [
        "KYORUGI - Fin Weight",
        "KYORUGI - Fly Weight",
        "KYORUGI - Bantam Weight",
        "KYORUGI - Feather Weight",
        "KYORUGI - Light Weight",
        "KYORUGI - Welter Weight",
        "KYORUGI - Lt Middle Weight",
        "POOMSAE - Group A - Individual",
        "POOMSAE - Group B - Individual",
        "POOMSAE - Team - Event",
        "POOMSAE - Mix Pair",
      ],
      WUSHU: [
        "Wushu – Girls (Group A) - 48kgs",
        "Wushu – Girls (Group A) - 52kgs",
        "Wushu – Girls (Group A) - 56kgs",
        "Wushu – Girls (Group B) - 42kgs",
        "Wushu – Girls (Group B) - 45kgs",
        "Wushu – Girls (Group B) - 48kgs",
      ],
      WRESTLING_FREESTYLE: [
        "Cadet 42kgs",
        "Cadet 46kgs",
        "Cadet 50kgs",
        "Cadet 54kgs",
        "Junior 54kgs",
        "Junior 58kgs",
        "Junior 62kgs",
        "Junior 66kgs",
      ],
    },
  },
  "PARA GAMES": {
          BOYS: {
        ATHLETICS: [
          "VI-100 M Dash – T11/TB",
          "VI-100 M Dash-T12/LV",
          "VI-100 M Dash-T13/LV",
          "VI-Running Long Jump T11/TB",
          "VI-Running Long Jump-T12/LV",
          "VI-Running Long Jump-T13/LV",
          "VI-Shot Put T11/TB",
          "VI-Shot Put T12/LV",
          "VI-Shot Put T13/LV",
          "ID-100M-15yrs old below (Youth)",
          "ID-100M-16-25yrs old below (Junior)",
          "ID-200M-15yrs old below (Youth)",
          "ID-200M-16-25yrs old below (Junior)",
          "ID-400M-15yrs old below (Youth)",
          "ID-400M-16-25yrs old below (Junior)",
          "ID-4x100M Relay-15yrs old below (Youth)",
          "ID-4x100M Relay-16-25yrs old below (Junior)",
          "ID-Running Long Jump-15yrs old below (Youth)",
          "ID-Running Long Jump-16-25yrs old below (Junior)",
          "ID-Sot Put-T14-15yrs old below (Youth)",
          "ID-Shot Put-T14-16-25yrs old below (Junior)",
          "Goal Boal (VI)",
        ],
        BOCCE: [
          "Bocce-Single T14",
          "Bocce Double T14",
          "Bocce-Mixed Doubles",
          "Bocce-Team",
        ],
        SWIMMING: [
          "OH-50M Ortho Special Event – Freestyle",
          "OH-50M Ortho Special Event – Backstroke",
          "OH-50M Ortho Special – Breaststroke",
          "ID-50M Freestyle",
          "ID-50M Butterfly",
          "ID-50M Backstroke",
          "ID-50M Breaststroke",
        ],
      },
      GIRLS: {
        ATHLETICS: [
          "VI-100 M Dash – T11/TB",
          "VI-100 M Dash-T12/LV",
          "VI-100 M Dash-T13/LV",
          "VI-Running Long Jump T11/TB",
          "VI-Running Long Jump-T12/LV",
          "VI-Running Long Jump-T13/LV",
          "VI-Shot Put T11/TB",
          "VI-Shot Put T12/LV",
          "VI-Shot Put T13/LV",
          "ID-100M-15yrs old below (Youth)",
          "ID-100M-16-25yrs old below (Junior)",
          "ID-200M-15yrs old below (Youth)",
          "ID-200M-16-25yrs old below (Junior)",
          "ID-400M-15yrs old below (Youth)",
          "ID-400M-16-25yrs old below (Junior)",
          "ID-4x100M Relay-15yrs old below (Youth)",
          "ID-4x100M Relay-16-25yrs old below (Junior)",
          "ID-Running Long Jump-15yrs old below (Youth)",
          "ID-Running Long Jump-16-25yrs old below (Junior)",
          "ID-Sot Put-T14-15yrs old below (Youth)",
          "ID-Shot Put-T14-16-25yrs old below (Junior)",
          "Goal Boal (VI)",
        ],
        BOCCE: [
          "Bocce-Single T14",
          "Bocce Double T14",
          "Bocce-Mixed Doubles",
          "Bocce-Team",
        ],
        SWIMMING: [
          "OH-50M Ortho Special Event – Freestyle",
          "OH-50M Ortho Special Event – Backstroke",
          "OH-50M Ortho Special – Breaststroke",
          "ID-50M Freestyle",
          "ID-50M Butterfly",
          "ID-50M Backstroke",
          "ID-50M Breaststroke",
        ],
      },
    },
};
